name: Android CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get gl4es latest commit hash
      id: gl4es-sha
      run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra refs/heads/master | grep -io '^\S*'))"
      shell: bash
      
    - name: Cache gl4es
      uses: actions/cache@v2
      id: gl4es-cache
      with:
        path: gl4es/libs
        key: gl4es-holy-android-shared-${{ steps.gl4es-sha.outputs.sha }}

    - name: Get gl4es
      if: steps.gl4es-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: 'PojavLauncherTeam/gl4es-114-extra'
        path: 'gl4es'

    - name: Build gl4es
      if: steps.gl4es-cache.outputs.cache-hit != 'true'
      continue-on-error: true
      run: |
        cd gl4es
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "github-actions"
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
        cp -R libs/* ../rsdkv5_proj/src/main/jniLibs/
    
    - name: Push gl4es
      if: github.event != 'pull_request' && steps.gl4es-cache.outputs.cache-hit != 'true'
      continue-on-error: true
      run: |
        git add .
        git commit -am "CI: Update gl4es"
        git push

    - name: Build apk
      run: |
        # Build the loader
        ./gradlew :rsdkv5_proj:assembleDebug
        mv rsdkv5_proj/build/outputs/apk/debug/rsdkv5_proj-debug.apk out/RSDKv5.apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: out/RSDKv5.apk
